export const styleNames = [
  'India Pale Ale (IPA)',
  'American Pale Ale',
  'Stout',
  'Porter'
].map(x => ({value: x, text: x, key: x}))

export const maltNames = [
  'Pilsen Light LME',
  'Golden Light LME',
  'Bavarian Wheat LME',
  'Munich LME',
  'Rye LME',
  'Traditional Dark LME'
].map(x => ({value: x, text: x, key: x}))

export const hopNames = [
  'Citra',
  'Galaxy',
  'Mosaic',
  'Vic Secret',
  'Motueka',
  'Cascade'
].map(x => ({value: x, text: x, key: x}))

export const yeastNames = [
  'Wyeast 1007 German Ale',
  'Wyeast 1010 American Wheat',
  'Wyeast 1026-PC British Cask Ale',
  'Wyeast 1028 London Ale',
  'Wyeast 1056 American Ale',
  'Wyeast 1084 Irish Ale',
  'Wyeast 1087-PC Wyeast Bohemian Ale Blend',
  'Wyeast 1098 British Ale',
  'Wyeast 1099 Whitebread Ale',
  'Wyeast 1187 Ringwood Ale',
  'Wyeast 1203-PC Burton IPA Blend',
  'Wyeast 1214 Belgian Abbey Style Ale',
  'Wyeast 1217-PC West Coast IPA',
  'Wyeast 1272 American Ale II',
  'Wyeast 1275 Thames Valled Ale',
  'Wyeast 1318 London Ale III',
  'Wyeast 1332 Northwest Ale',
  'Wyeast 1335 British Ale II',
  'Wyeast 1388 Belgian Strong Ale',
  'Wyeast 1450 Denny\'s Favorite 50 Ale',
  'Wyeast 1469 West Yorkshire Ale',
  'Wyeast 1581-PC Belgian Stout',
  'Wyeast 1728 Scottish Ale',
  'Wyeast 1762 Belgian Abble Style Ale II',
  'Wyeast 1768-PC English Special Bitter',
  'Wyeast 1882-PC Thames Valley Ale II',
  'Wyeast 1968 London ESB Ale',
  'Wyeast 2000-PC Budvar Lager',
  'Wyeast 2001-PC Pislner Urquell H-Strain',
  'Wyeast 2002-PC Gambrinus Style Lager',
  'Wyeast 2007 Pilsen Lager',
  'Wyeast 2035-PC American Lager',
  'Wyeast 2042-PC Danish Lager',
  'Wyeast 2105-PC Rocky Mountain Lager',
  'Wyeast 2112 California Lager',
  'Wyeast 2124 Bohemian Lager',
  'Wyeast 2206 Bavarian Lager',
  'Wyeast 2247-PC European Lager',
  'Wyeast 2272-PC North American Lager',
  'Wyeast 2278 Czech Pils',
  'Wyeast 2308 Munich Lager',
  'Wyeast 2352-PC Munich Lager II',
  'Wyeast 2487-PC Hella-Bock Lager',
  'Wyeast 2565 Kolsch',
  'Wyeast 2575-PC Kolsch Yeast II',
  'Wyeast 2633 Octoberfest Lager Blend',
  'Wyeast 2782-PC Staro Prague Lager',
  'Wyeast 3031-PC Saison-Brett Blend',
  'Wyeast 3056 Bavarian Wheat Blend',
  'Wyeast 3068 Weihenstephan Weizen',
  'Wyeast 3191-PC Berliner Weisse Blend',
  'Wyeast Oud Bruin Ale Blend',
  'Wyeast 3278 Belgian Lambic Blend',
  'Wyeast 3333-PC German Wheat',
  'Wyeast 3463-PC Forbidden Fruit',
  'Wyeast 3522 Belgian Ardennes',
  'Wyeast 3538-PC Leuven Ple Ale',
  'Wyeast 3638 Bavarian Wheat',
  'Wyeast 3655-PC Belgian Schelde Ale',
  'Wyeast 3711 French Saison',
  'Wyeast 3724 Belgian Saison',
  'Wyeast 3725-PC Biere de Garde',
  'Wyeast 3726 Farmhouse Ale',
  'Wyeast 3739-PC Flanders Golden Ale',
  'Wyeast 3763 Roeselare Ale Blend',
  'Wyeast 3787 Trappish Style High Gravity',
  'Wyeast 3789-PC Trappish Style Blend',
  'Wyeast 3822-PC Belgian Dark Ale',
  'Wyeast 3864-PC Canadian/Belgian Ale',
  'Wyeast 3942-PC Belgian Wheat',
  'Wyeast 3944 Belgian Witbier',
  'Wyeast 9097-PC Old Ale Blend',
  'Safale US-05',
  'Safale US-06',
  'Danstar Munich'
].map(x => ({value: x, text: x, key: x}))